import { Event, EventData } from "../index";
import { Common } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * General event for tracking errors returned by the blockchain sdk
 */
export interface BlockchainSdkError extends EventData {
	event_name: "blockchain_sdk_error";
	event_type: "log";
	common: Common;
	error_reason: string;
	offer_id: string;
	order_id: string;
}

export function create(user_id: string, error_reason: string, offer_id: string, order_id: string): Event<BlockchainSdkError> {
	return new Event<BlockchainSdkError>({
		event_name: "blockchain_sdk_error",
		event_type: "log",
		common: Event.common(user_id),
		error_reason,
		offer_id,
		order_id
	});
}
