import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Server submits earn transaction to blockchain and get confirmation
 */
export interface EarnTransactionBroadcastToBlockchainSucceeded extends EventData {
	event_name: "earn_transaction_broadcast_to_blockchain_succeeded";
	event_type: "log";
	common: Common;
	transaction_id: string;
	offer_id: string;
	order_id: string;
}

export function create(user_id: string, transaction_id: string, offer_id: string, order_id: string): Event<EarnTransactionBroadcastToBlockchainSucceeded> {
	return new Event<EarnTransactionBroadcastToBlockchainSucceeded>({
		event_name: "earn_transaction_broadcast_to_blockchain_succeeded",
		event_type: "log",
		common: createCommon(user_id),
		transaction_id,
		offer_id,
		order_id
	});
}
