import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * blocking cross app wallet restore
 */
export interface RestoreRequestFailed extends EventData {
	event_name: "restore_request_failed";
	event_type: "log";
	common: Common;
	error_reason: string;
}

export function create(user_id: string, device_id: string, error_reason: string): Event<RestoreRequestFailed> {
	return new Event<RestoreRequestFailed>({
		event_name: "restore_request_failed",
		event_type: "log",
		common: createCommon(user_id, device_id),
		error_reason
	});
}
