import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Server fails to create spend transaction on blockchain
 */
export interface SpendTransactionBroadcastToBlockchainFailed extends EventData {
	event_name: "spend_transaction_broadcast_to_blockchain_failed";
	event_type: "log";
	common: Common;
	error_reason: string;
	offer_id: string;
	order_id: string;
}

export function create(user_id: string, error_reason: string, offer_id: string, order_id: string): Event<SpendTransactionBroadcastToBlockchainFailed> {
	return new Event<SpendTransactionBroadcastToBlockchainFailed>({
		event_name: "spend_transaction_broadcast_to_blockchain_failed",
		event_type: "log",
		common: createCommon(user_id),
		error_reason,
		offer_id,
		order_id
	});
}
