import { Event, EventData } from "../index";
import { Common } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Phase 1 - stellar account creation failed
 */
export interface StellarAccountCreationFailed extends EventData {
	event_name: "stellar_account_creation_failed";
	event_type: "log";
	common: Common;
	error_reason: string;
}

export function create(user_id: string, error_reason: string): Event<StellarAccountCreationFailed> {
	return new Event<StellarAccountCreationFailed>({
		event_name: "stellar_account_creation_failed",
		event_type: "log",
		common: Event.common(user_id),
		error_reason
	});
}
