import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * User logout per device_id and user_id combination
 */
export interface UserLogoutServerRequested extends EventData {
	event_name: "user_logout_server_requested";
	event_type: "business";
	common: Common;
}

export function create(user_id: string, device_id: string): Event<UserLogoutServerRequested> {
	return new Event<UserLogoutServerRequested>({
		event_name: "user_logout_server_requested",
		event_type: "business",
		common: createCommon(user_id, device_id)
	});
}
