import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * when a user login with a different device /user_id , and this device is currently logout
 */
export interface UserLoginServerRequested extends EventData {
	event_name: "user_login_server_requested";
	event_type: "business";
	common: Common;
}

export function create(user_id: string, device_id: string): Event<UserLoginServerRequested> {
	return new Event<UserLoginServerRequested>({
		event_name: "user_login_server_requested",
		event_type: "business",
		common: createCommon(user_id, device_id)
	});
}
