import { Event, EventData } from "../index";
import { Common } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Stellar account/wallet successfully created for the user
 */
export interface WalletCreationSucceeded extends EventData {
	event_name: "wallet_creation_succeeded";
	event_type: "business";
	common: Common;
}

export function create(user_id: string): Event<WalletCreationSucceeded> {
	return new Event<WalletCreationSucceeded>({
		event_name: "wallet_creation_succeeded",
		event_type: "business",
		common: Event.common(user_id)
	});
}
