import { Event, EventData } from "../index";
import { Common, create as createCommon } from "./common";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Wallet address updated successfully
 */
export interface WalletAddressUpdateSucceeded extends EventData {
	event_name: "wallet_address_update_succeeded";
	event_type: "log";
	common: Common;
}

export function create(user_id: string): Event<WalletAddressUpdateSucceeded> {
	return new Event<WalletAddressUpdateSucceeded>({
		event_name: "wallet_address_update_succeeded",
		event_type: "log",
		common: createCommon(user_id)
	});
}
